### PR TITLE
Use proxy objects to eliminate use of eval()

### PR DESCRIPTION
**Pull request by noahm**
I'm a big fan of this library and have come to the conclusion that it's the only realistic option available for managing immutable data in a Typescript project. Unfortunately, security requirements of my latest project include `content-security-policy` headers which prevents the use of eval at the browser level. After a lot of research looking for alternative libraries (there aren't any) and a bit of research into javascript meta-programming I arrived at the following solution.

I have replaced the core string parsing approach of the library by passing a Proxy object to the `getProp` function that traces the access path of the returned data. There are no changes to the public interface and tests pass locally, but testing in IE 11 will need a polyfill (see below).

### On performance
This eliminates the fixed cost of parsing the `getProp` function and trades it for a cost per level of depth when writing. In practice reads are unaffected, shallow writes are faster, and very deep writes are slower.

### On compatibility
Proxy objects [are supported in all modern browsers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy#Browser_compatibility) and support can be added to legacy browsers with the very small [`proxy-polyfill`](https://github.com/GoogleChrome/proxy-polyfill) from Google. I could see an argument for making it an optional dependency and auto-including it from within ImmutableAssign but I have not done that here.

### CODE REVIEW

**Comment by engineforce** [comment]
Thanks for your pull request, you have make a lot of changes, I would like to take some time to evaluate it and see what is the impact on browsers/nodejs support and performance. 

Can you please check if **new Function()** instead of **eval()** works under CSP?

**Comment by noahm** [comment]
Of course, take your time reviewing. It _is_ a big change, after all. Definitely a `1.1.0` if not a `2.0.0` given the scope of the rewrite.

Under CSP `new Function()` will not work when `unsafe-eval` is disabled. Refer to [Content Security Policy Level 2 spec](https://www.w3.org/TR/CSP2/#directive-script-src)

> If 'unsafe-eval' is not in allowed script sources:
> * Instead of evaluating their arguments, both operator eval and function eval MUST throw an EvalError exception. 
> * When called as a constructor, the function Function MUST throw an EvalError exception. 
>
> ...

**Comment by TN1ck** [comment]
I just tried out this branch to check if it works with my tests and it actually didn't, I try to provide some test cases in the near time where it failed. Although, I really like the idea of using Proxies for this, ditching eval is always good. https://github.com/kube/monolite is doing something similar as this library and works with proxies, it might be worth to check out how they are doing it.

**Comment by abierbaum** [comment]
Came here to say the same thing.  I think this library looks great but we can't use it because of the eval.  I wish we could though because having full typescript type checking would be great.

**Comment by evnix** [comment]
+1 for this. we recently started using this library on a huge project, this helps us a lot keeping things clean where immutable would infect our entire codebase and getting rid of eval is definitely a big plus.

**Comment by noahm** [comment]
Thanks for getting all this in! I'll have one small follow-up PR shortly based on the polyfill you added afterwards.

**Pull request merged**
